<h1> Deprecated

In [ ]:
import pandas as pd
import numpy as np
import os

In [155]:
calendar = pd.read_csv("data/calendar.csv")

In [156]:
prices = pd.read_csv("data/sell_prices.csv")

In [157]:
train = pd.read_csv("data/sales_train_validation.csv")

In [1]:
import pandas as pd
import numpy as np

class M5TimeSeriesSplit:

    def __init__(self, n_days, days_columns, fixed_columns=None, 
                 sliding_window=True, return_index=True,
                 rename=False):
        
        self.n_days = n_days
        self.days_columns = days_columns
        self.fixed_columns = fixed_columns
        self.sliding_window = sliding_window
        self.return_index = return_index
        self.rename = rename
        
        assert isinstance(days_columns, list)
        assert isinstance(fixed_columns, list)

    def split(self, X, y=None):

        for day in range(self.n_days):
            X_train, y_train, X_test, y_test = self.create_split(day, X, y)
            
            if self.rename:
                y_test.columns = [f"F{day+1}"]
            yield X_train, y_train, X_test, y_test

    def create_split(self, day, X, y=None):
        
        if self.sliding_window:
            tr_day0 = day
            te_day0 = day + 1
        else: 
            tr_day0 = 0
            te_day0 = 0
        
        
        tr_x = self.fixed_columns + self.days_columns[tr_day0:-(self.n_days + 1)]
        tr_y = [self.days_columns[-(self.n_days - day + 1)]]
        te_x = self.fixed_columns + self.days_columns[te_day0:-(self.n_days)]
        te_y = [self.days_columns[-(self.n_days - day)]]
        
        
        if self.return_index:
            return tr_x, tr_y, te_x, te_y
        
        return X[tr_x], X[tr_y], X[te_x], X[te_y]
    
ts = M5TimeSeriesSplit(n_days=28, 
                       days_columns=train.columns[6:].tolist(),
                       fixed_columns=train.columns[:6].tolist(),
                       return_index=False,
                       rename=True)

NameError: name 'train' is not defined

In [165]:
from sklearn.linear_model import LinearRegression

In [169]:
id_columns = ["id", "item_id", "dept_id", "cat_id", "store_id", "state_id"]

,d_1,d_2,d_3,d_4,d_5,d_6,d_7,d_8,d_9,d_10,...,d_1885,d_1886,d_1887,d_1888,d_1889,d_1890,d_1891,d_1892,d_1893,d_1894
0,0,0,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,1,0,4
1,0,0,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,0,0,0,0,0,0,0,0,0,0,...,6,0,0,0,0,3,1,2,1,3
4,0,0,0,0,0,0,0,0,0,0,...,0,1,0,4,4,0,1,4,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30485,0,0,2,2,0,3,1,4,1,0,...,0,0,0,0,0,0,0,0,0,0
30486,0,0,0,0,0,5,0,1,1,3,...,0,0,0,0,0,0,1,1,2,0
30487,0,6,0,2,2,4,1,8,5,2,...,1,1,0,0,0,0,1,1,2,1
30488,0,0,0,0,0,0,0,0,0,0,...,4,3,0,0,0,0,0,1,1,2
30489,0,0,0,0,0,0,0,0,0,0,...,5,7,3,1,4,3,3,1,2,3

In [211]:
predictions = pd.DataFrame()
i = 1
for X_tr, y_tr, X_te, y_te in ts.split(train):
    print(i)
    reg = LinearRegression()
    reg.fit(X_tr.drop(columns=id_columns).values, y_tr)
    predictions[f"F{i}"] = reg.predict(X_te.drop(columns=id_columns).values)[:,0]
    i += 1
#     prediction = X_te.iloc[:,-1:]

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28

In [212]:
e = WRMSSEEvaluator(train.iloc[:,:-28], train.iloc[:,-28:], calendar, prices)

HBox(children=(IntProgress(value=0, max=12), HTML(value='')))

HBox(children=(IntProgress(value=0, max=12), HTML(value='')))

HBox(children=(IntProgress(value=0, max=12), HTML(value='')))

HBox(children=(IntProgress(value=0, max=42840), HTML(value='')))

In [214]:
predictions.columns = train.iloc[:,-28:].columns

predictions[predictions<0] = 0

In [215]:
e.score(predictions)

5.606367917298682

In [216]:
predictions

,d_1886,d_1887,d_1888,d_1889,d_1890,d_1891,d_1892,d_1893,d_1894,d_1895,...,d_1904,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913
0,0.771290,1.782398,0.959270,1.050791,0.000000,1.000110,1.975069,1.097245,0.287735,0.018262,...,0.000000,0.000000,0.031782,0.656122,0.000000,0.000000,0.000000,0.000000,0.108635,0.306037
1,0.000000,0.902383,0.655969,0.502143,0.000000,0.000000,1.653961,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.027272,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,2.471598,1.257610,1.507360,0.000000,0.000000,2.283168,1.843101,0.136592,0.000000,1.173999,...,0.075626,0.000000,0.834938,0.000000,1.445875,0.000000,0.000000,2.009121,0.337034,1.182587
3,5.114100,0.432976,0.000000,0.000000,0.000000,0.000000,2.231740,0.000000,0.000000,0.367270,...,0.000000,0.000000,0.000000,0.000000,0.000000,6.703906,6.758224,5.437533,10.143164,0.286786
4,0.000000,0.000000,0.031101,0.000000,2.098964,0.000000,1.362826,0.000000,0.000000,0.223715,...,0.478362,0.663828,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.995102,0.826087
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30485,0.000000,0.000000,0.366819,0.098579,3.802620,0.000000,0.090248,0.000000,0.151346,0.000000,...,0.000000,0.615675,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.586443,0.000000
30486,2.925543,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,5.776440,0.000000,0.000000,10.134934,12.437876,3.630387,6.901473,0.000000
30487,0.000000,0.000000,0.000000,0.000000,0.108165,0.000000,0.905767,0.000000,0.000000,0.602852,...,0.000000,0.220972,0.000000,0.000000,0.000000,1.418187,1.491173,0.000000,2.622614,0.000000
30488,3.194184,1.063557,1.996847,0.000000,0.353978,3.992132,1.819694,1.020117,1.464483,3.432575,...,2.455099,0.955558,2.213894,0.000000,2.843388,1.729103,1.151654,3.028266,2.329076,2.428680
30489,9.552226,3.667363,4.420772,0.000000,0.000000,7.755610,2.161713,2.687262,1.199518,7.686647,...,5.225347,1.869535,4.426149,0.000000,6.189988,3.575730,0.937217,8.451522,2.565195,3.412589

In [219]:
submission = pd.read_csv("data/sample_submission.csv")

In [223]:
submission.iloc[:predictions.shape[0],1:] = predictions.values

In [227]:
submission.to_csv("submission_2.csv", index=False)

In [228]:
submission

,id,F1,F2,F3,F4,F5,F6,F7,F8,F9,...,F19,F20,F21,F22,F23,F24,F25,F26,F27,F28
0,HOBBIES_1_001_CA_1_validation,0.771290,1.782398,0.959270,1.050791,0.000000,1.000110,1.975069,1.097245,0.287735,...,0.000000,0.000000,0.031782,0.656122,0.000000,0.000000,0.000000,0.000000,0.108635,0.306037
1,HOBBIES_1_002_CA_1_validation,0.000000,0.902383,0.655969,0.502143,0.000000,0.000000,1.653961,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.027272,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,HOBBIES_1_003_CA_1_validation,2.471598,1.257610,1.507360,0.000000,0.000000,2.283168,1.843101,0.136592,0.000000,...,0.075626,0.000000,0.834938,0.000000,1.445875,0.000000,0.000000,2.009121,0.337034,1.182587
3,HOBBIES_1_004_CA_1_validation,5.114100,0.432976,0.000000,0.000000,0.000000,0.000000,2.231740,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,6.703906,6.758224,5.437533,10.143164,0.286786
4,HOBBIES_1_005_CA_1_validation,0.000000,0.000000,0.031101,0.000000,2.098964,0.000000,1.362826,0.000000,0.000000,...,0.478362,0.663828,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.995102,0.826087
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60975,FOODS_3_823_WI_3_evaluation,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
60976,FOODS_3_824_WI_3_evaluation,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
60977,FOODS_3_825_WI_3_evaluation,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
60978,FOODS_3_826_WI_3_evaluation,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
60979,FOODS_3_827_WI_3_evaluation,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000